version: "3"
services:
  app_dev:
    container_name: app_dev
    build:
      context: .
      dockerfile: ./dockerfile/react/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    ports:
      - target: 3000
        published: ${APP_PORT:-3000}
        protocol: tcp
        mode: host
    tty: true
  nginx_dev:
    container_name: nginx_dev
    image: nginx:1.25
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - type: bind
        source: ./dockerfile/nginx/config/conf.d
        target: /etc/nginx/conf.d
    ports:
      - target: 80
        published: ${NGINX_PORT:-80}
        protocol: tcp
        mode: host
    depends_on:
      - app_dev
